name: jrnl-sh
version: '2.8.4'
summary: jrnl: the command-line journaling app
description: |
  Collect your thoughts and notes without leaving the command line.
confinement: strict
base: core20

grade: stable

parts:
  jrnl:
    plugin: python
    source: https://files.pythonhosted.org/packages/11/5c/dfbccbe2d5042b89240c9e3af48aa8c79c462981330e397b656490a9b997/jrnl-2.8.4.tar.gz

apps:
  jrnl:
    command: bin/jrnl
    plugs:
      - home
